# Generated by Django 4.2.6 on 2024-08-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementprovider',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='statementprovider',
            name='proposed_price',
        ),
        migrations.RemoveField(
            model_name='statementprovider',
            name='response_text',
        ),
    ]
