# Generated by Django 4.2.6 on 2025-06-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWallMaterialChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Материал наружных стен',
                'verbose_name_plural': 'Материалы наружных стен',
            },
        ),
        migrations.CreateModel(
            name='HeatingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Отопление',
                'verbose_name_plural': 'Отопление',
            },
        ),
        migrations.CreateModel(
            name='InnerWallMaterialChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Внутренние стены и перегородки',
                'verbose_name_plural': 'Внутренние стены и перегородки',
            },
        ),
        migrations.CreateModel(
            name='LightingTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Освещение',
                'verbose_name_plural': 'Освещения',
            },
        ),
        migrations.CreateModel(
            name='RoofChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип кровли',
                'verbose_name_plural': 'Типы кровли',
            },
        ),
        migrations.CreateModel(
            name='SecurityChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Объект охраняется',
                'verbose_name_plural': 'Объект охраняется',
            },
        ),
        migrations.CreateModel(
            name='StairsClassificationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Н1', 'Лестничные клетки с входом на лестничную клетку с этажа через наружную воздушную зону по открытым переходам'), ('Н2', 'Лестничные клетки с подпором воздуха на лестничную клетку при пожаре'), ('L1', 'Лестничные клетки с естественным освещением через остекленные или открытые проемы в наружных стенах на каждом этаже'), ('L2', 'Лестничные клетки с естественным освещением через остекленные или открытые проемы в покрытии'), ('L3', 'Лестничные клетки с естественным освещением через остекленные или открытые проемы в наружных стенах на каждом этаже и в покрытии')], default='Н1', max_length=2)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Классификация Лестниц(Н1,Н2,L1,L2,L3)',
                'verbose_name_plural': 'Классификация Лестниц(Н1,Н2,L1,L2,L3)',
            },
        ),
        migrations.CreateModel(
            name='StairsMaterialChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Материал лестницы',
                'verbose_name_plural': 'Материалы лестниц',
            },
        ),
        migrations.CreateModel(
            name='StairsTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип лестницы',
                'verbose_name_plural': 'Типы лестниц',
            },
        ),
        migrations.CreateModel(
            name='VentilationTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Вентиляция',
                'verbose_name_plural': 'Вентиляции',
            },
        ),
    ]
