# Generated by Django 4.2.6 on 2024-01-05 11:09

import auths.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[auths.validators.validate_alpha], verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[auths.validators.validate_alpha], verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[auths.validators.validate_alpha], verbose_name='отчество'),
        ),
    ]
