# Generated by Django 4.2.6 on 2024-01-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_customuser_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-id',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
