# Generated by Django 4.2.6 on 2024-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Гражданин'), ('OBJECT_OWNER', 'Собственник объекта'), ('INSPECTOR', 'Инспектор'), ('ADMIN', 'Админ'), ('OPERATOR', 'Оператор'), ('FIRE_DEPARTMENT', 'Пожарная часть')], max_length=100, verbose_name='роль'),
        ),
    ]
