# Generated by Django 4.2.6 on 2024-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Принято'), ('NOT_ACCEPTED', 'Не принято')], default='NOT_ACCEPTED', help_text='Гражданин не имеет статуса', max_length=20, null=True),
        ),
    ]
