# Generated by Django 4.2.6 on 2024-04-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
