# Generated by Django 4.2.6 on 2024-04-16 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iin',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='IIN must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='иин'),
        ),
    ]
