# Generated by Django 4.2.6 on 2025-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0011_category_customuserrole_remove_customuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='actual_residence_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес фактического проживания гражданина'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='residence_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес прописки гражданина'),
        ),
    ]
