# Generated by Django 4.2.6 on 2025-06-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0012_auto_20250618_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inspector_jurisdiction_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город юрисдикции инспектора'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='inspector_jurisdiction_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район юрисдикции инспектора'),
        ),
    ] 