# Generated by Django 4.2.6 on 2025-06-18 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0013_auto_20250618_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'роли пользователей', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_organization_type',
            field=models.CharField(choices=[('Commercial Organizations', 'Коммерческие Организации'), ('NonCommercial Organizations', 'Не Коммерческие Организации')], default='Commercial Organizations', max_length=50, verbose_name='Главный тип организации(Коммерческое или НеКоммерческое)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_sub_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ПодТип Организации'),
        ),
        migrations.AddField(
            model_name='education',
            name='performing_now',
            field=models.BooleanField(default=False, verbose_name='Учусь здесь сейчас'),
        ),
        migrations.AddField(
            model_name='experience',
            name='performing_now',
            field=models.BooleanField(default=False, verbose_name='Работаю тут сейчас'),
        ),
        migrations.AddField(
            model_name='otherachievement',
            name='performing_now',
            field=models.BooleanField(default=False, verbose_name='Делаю другие достижения сейчас'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bin_field',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='BIN must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='бин'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.TextField(blank=True, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization_name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization_type',
            field=models.CharField(choices=[('State-owned enterprises(Commercial)', 'Государственные предприятия(Коммерческая)'), ('Business partnerships(Commercial)', 'Хозяйственные товарищества(Коммерческая)'), ('Joint stock company(Commercial)', 'Акционерное общество(Коммерческая)'), ('Production cooperative(Commercial)', 'Производственный кооператив(Коммерческая)'), ('Institutions(NonCommercial)', 'Учреждения(Не Коммерческая)'), ('Public Association(NonCommercial)', 'Общественное объединение(Не Коммерческая)'), ('Joint stock company(NonCommercial)', 'Акционерное общество(Не Коммерческая)'), ('Consumer Cooperative(NonCommercial)', 'Потребительский кооператив(Не Коммерческая)'), ('Fund(NonCommercial)', 'Фонд(Не Коммерческая)'), ('Religious associations(NonCommercial)', 'Религиозные объединения(Не Коммерческая)'), ('Associations of individual entrepreneurs and (or) legal entities in the form of an association (union)(NonCommercial)', 'Объединения индивидуальных предпринимателей и (или) юридических лиц в форме ассоциации (союза)(Не Коммерческая)'), ('Other forms provided for by law(NonCommercial)', 'Иные формы, предусмотренные законодательством(Не Коммерческая)')], default='State-owned enterprises(Commercial)', max_length=200, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Chief State Inspector for Fire Control', 'Главный государственный инспектор по пожарному контролю'), ('Chief Inspector of Fire Control', 'Старший инспектор по пожарному контролю'), ('Fire Control Inspector', 'Инспектор по пожарному контролю')], default='Chief State Inspector for Fire Control', max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('Private civil protection', 'Рядовой гражданской защиты'), ('Junior Sergeant of Civil Protection', 'Младший сержант гражданской защиты'), ('Civil Protection Sergeant', 'Сержант гражданской защиты'), ('Senior Sergeant of Civil Protection', 'Старший сержант гражданской защиты'), ('Civil Protection Foreman', 'Старшина гражданской защиты'), ('Second Lieutenant of Civil Protection', 'Младший лейтенант гражданской защиты'), ('Lieutenant of Civil Protection', 'Лейтенант гражданской защиты'), ('Senior Lieutenant of Civil Protection', 'Старший лейтенант гражданской защиты'), ('Captain of Civil Protection', 'Капитан гражданской защиты'), ('Major of Civil Protection', 'Майор гражданской защиты'), ('Lieutenant Colonel of Civil Protection', 'Подполковник гражданской защиты'), ('Colonel of Civil Protection', 'Полковник гражданской защиты'), ('Major General of Civil Protection', 'Генерал-майор гражданской защиты'), ('Lieutenant General of Civil Protection', 'Генерал-лейтенант гражданской защиты'), ('Colonel-General of Civil Protection', 'Генерал-полковник гражданской защиты')], default='Private civil protection', max_length=50, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='role',
            field=models.CharField(choices=[('PROVIDER', 'Provider')], default='PROVIDER', max_length=50),
        ),
    ]
