# Generated by Django 4.2.6 on 2025-06-18 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_alter_userrole_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='IIN must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='иин'),
        ),
    ]
