# Generated by Django 4.2.6 on 2024-01-11 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentkey',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentkeyfile',
            options={},
        ),
        migrations.CreateModel(
            name='BuildingCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='objects.building')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
