# Generated by Django 4.2.6 on 2024-01-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_document_options_alter_documentcomment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvacAddresses',
            new_name='EvacAddress',
        ),
    ]
