# Generated by Django 4.2.6 on 2024-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_rename_evacaddresses_evacaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evacaddress',
            name='scan_link',
        ),
        migrations.AddField(
            model_name='evacaddress',
            name='file_path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='public/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='evacaddress',
            name='qrcode_url',
            field=models.URLField(max_length=255, verbose_name='qrcode ссылка'),
        ),
    ]
