# Generated by Django 4.2.6 on 2024-01-11 11:20

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_remove_evacaddress_scan_link_evacaddress_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacaddress',
            name='file_path',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(location='public/'), upload_to='public/', verbose_name='файл'),
        ),
    ]
