# Generated by Django 4.2.6 on 2024-01-11 12:03

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_evacaddress_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentkeyfile',
            name='path',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(location='isec/'), upload_to='%Y/%m/', verbose_name='путь'),
        ),
        migrations.AlterField(
            model_name='evacaddress',
            name='file_path',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(location='public/'), upload_to='%Y/%m/', verbose_name='файл'),
        ),
    ]
