# Generated by Django 4.2.6 on 2024-01-12 06:43

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_documentkeyfile_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacaddress',
            name='file_path',
            field=models.FileField(blank=True, max_length=2048, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(location='public/'), upload_to='%Y/%m/', verbose_name='файл'),
        ),
    ]
