# Generated by Django 4.2.6 on 2024-01-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_alter_evacaddress_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentkeyfile',
            name='path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='private/%Y/%m/', verbose_name='путь'),
        ),
        migrations.AlterField(
            model_name='evacaddress',
            name='file_path',
            field=models.FileField(blank=True, max_length=2048, null=True, upload_to='public/%Y/%m/', verbose_name='файл'),
        ),
    ]
