# Generated by Django 4.2.6 on 2024-01-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_alter_evacaddress_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='option',
        ),
        migrations.AddField(
            model_name='building',
            name='fire_resistance_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='organization_object',
            field=models.CharField(blank=True, choices=[('BUILDING', 'Здание'), ('CONSTRUCTION', 'Сооружение'), ('DIFFERENT CONSTRUCTION', 'Иная конструкция')], max_length=255, null=True),
        ),
    ]
