# Generated by Django 4.2.6 on 2024-02-29 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0010_remove_building_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='inspector',
            field=models.ManyToManyField(blank=True, null=True, related_name='inspected_buildings', to=settings.AUTH_USER_MODEL, verbose_name='инспектор'),
        ),
    ]
