# Generated by Django 4.2.6 on 2024-02-29 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0011_building_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='inspector',
            field=models.ManyToManyField(blank=True, related_name='inspected_buildings', to=settings.AUTH_USER_MODEL, verbose_name='инспектор'),
        ),
    ]
